### ISSUE TITLE
A request for the PyPI name that this project uses, i.e., `hugo`

### ISSUE THREAD

**Issue by agriyakhetarpal** [nariman/hugo#4]
Hi, @nariman!

I am reaching out because I believe that this project has been published to PyPI under the name `hugo` – however, it has [not received an update](https://pypi.org/project/hugo/#history) in the last five years and does not seem to be maintained on this GitHub repository.

I am the author of a Python package at https://github.com/agriyakhetarpal/hugo-python-distributions which provides binaries for the [Hugo static site generator](https://gohugo.io/) written in [Golang](https://go.dev/). I have published it to PyPI under the name `python-hugo` at this time—considering the pre-existence of this project—and under a different versioning scheme (a modified instance of the CalVer standard). I was wondering if it would be possible for you to consider removing this project, `hugo`, from PyPI or allowing me to replace it with my project under the provisions of the [PEP 541](https://peps.python.org/pep-0541/) document and guidelines.

Doing this will allow me to publish my project under the name `hugo` and publish `pip`-installable binaries for the extended edition of Hugo, whose versioning can then be aligned with the [Hugo releases themselves](https://github.com/gohugoio/hugo/releases) rather than my own scheme, for the ease of use for users of Hugo given its prevalence in the technical writing and personal blogging arenas.

I was considering contacting [PyPI support](https://github.com/pypi/support/issues/new?assignees=&labels=PEP+541&projects=&template=pep541-request.yml&title=PEP+541+Request:+PROJECT_NAME) for this task of re-association, but I thought it would be amicable to reach out to the maintainers of the project and see if they can work something out before doing so.

I am in the hopes that we can get to a solution herewith that benefits both parties.

Regards,
Agriya Khetarpal

**Comment by nariman** [comment]
Hello, @agriyakhetarpal!

Actually, I'm not sure why I've published my package in the first place. Some ideas, probably... that are no longer relevant.  
So I'm happy to give up the `hugo` name on PyPI.

I have concerns about if it would be ok to distribute prebuilt binaries of Hugo under the `hugo` name, due to this would be an unofficial distribution channel with the same product name.  
I hope you'll use the package name responsibly.

To not create any time gap between project deletion and new project creation, I think it's better to add you as a project owner. Then you can remove me from the project.  
If that's ok for you, please leave your PyPI username.

**Comment by agriyakhetarpal** [comment]
Thank you for your prompt response, @nariman.

> I have concerns about if it would be ok to distribute prebuilt binaries of Hugo under the hugo name, due to this would be an unofficial distribution channel with the same product name.

I agree – I am aware of these software licensing concerns, especially if I distribute unofficial binaries under the same name on PyPI. I am currently distributing Hugo with my packaging code being under the Apache license, and Hugo distributes it under the same license as well. The Apache license is one of the more permissive ones out there and it grants me permission to provide pre-existing software (binaries, in my case) to users without retaining the source code use for compiling it in its original form.

For further compliance, I am providing a copy of Hugo's license in both the GitHub repository itself and in the source distribution. I will make sure to add a note about how this is not affiliated with Hugo or its governing bodies (yet).

> I hope you'll use the package name responsibly.

Absolutely. I intend to publicise this package in many areas and on the Hugo discourse forums after our correspondence, where I can include other people into the mix and let them know that I plan to maintain this package (maybe get it to be official too, for those who would like using this `pip`-installed rendition).

> To not create any time gap between project deletion and new project creation, I think it's better to add you as a project owner. Then you can remove me from the project. If that's ok for you, please leave your PyPI username.

That's a good idea, I can then be safe from any potential name squatters, modify your project as per my requirements, remove older releases (`0.5.2`, etc.), and push releases from environments under my own repository (while deleting the recent releases for `python-hugo` afterwards). Is that what you meant?

My PyPI username is `agriyakhetarpal`. This is the link to my profile: https://pypi.org/user/agriyakhetarpal

**Comment by nariman** [comment]
I've removed current releases and sent you invite for the owner role. Please check if everything is ok.

<img src="https://github.com/nariman/hugo/assets/6004127/61518388-df06-4127-a27c-a1d63a4e8792" width="50%">

**Comment by agriyakhetarpal** [comment]
That is perfect – I have accepted the invite. Thank you for your cooperation! Should I remove you when I have my own releases ready, going forward?

**Comment by agriyakhetarpal** [comment]
That is perfect – I have accepted the invite. Thank you for your cooperation! Should I go ahead and remove you from the project, when I have my own release set up?

**Comment by nariman** [comment]
For security reasons, you should not keep me as the project owner. Some other type of attribution would be nice.

**Comment by agriyakhetarpal** [comment]
Agreed. Would it be fine for you to get listed in a Footnotes section of the `README.md` file, perhaps, as a note of appreciation for your kind gesture? I am open to further ideas as well. Really, thanks a lot!

**Comment by nariman** [comment]
> Would it be fine for you to get listed in a Footnotes section of the `README.md` file, perhaps, as a note of appreciation for your kind gesture?

Sounds good to me.
